/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev` / `next build`.
// Do not edit it by hand — it's committed here only so the project has
// valid types before you run it for the first time.
